package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import modelo.Conexion;

public class MainMenu extends javax.swing.JFrame {

    public MainMenu() {

        setTitle("Menú de Inicio");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(517, 540);
        setResizable(false);
        setLocationRelativeTo(null);

        JPanel panel = new JPanel();
        getContentPane().add(panel);

        // Crear un JLabel con la imagen de fondo
        ImageIcon backgroundImage = new ImageIcon(getClass().getClassLoader().getResource("imagenes/logo1.png"));
        JLabel backgroundLabel = new JLabel(backgroundImage);
        backgroundLabel.setBounds(0, 0, backgroundImage.getIconWidth(), backgroundImage.getIconHeight());
        panel.add(backgroundLabel);

        // Establecer el diseño del panel como nulo para poder posicionar los componentes libremente
        panel.setLayout(null);

        // Botones
        JButton btnIniciarSesionCliente = new JButton("Iniciar Sesión: Clientes");
        JButton btnIniciarSesionEmpleado = new JButton("Iniciar Sesión: Empleados");
        JButton btnRegistrarCliente = new JButton("Registrar Cliente");
        JButton btnSalir = new JButton("Salir");

        // Establecer la posición y tamaño de los botones
        btnIniciarSesionCliente.setBounds(50, 50, 180, 30);
        btnIniciarSesionEmpleado.setBounds(50, 90, 180, 30);
        btnRegistrarCliente.setBounds(50, 130, 180, 30);
        btnSalir.setBounds(50, 170, 180, 30);

        // Agregar botones al panel
        panel.add(btnIniciarSesionCliente);
        panel.add(btnIniciarSesionEmpleado);
        panel.add(btnRegistrarCliente);
        panel.add(btnSalir);

        panel.setComponentZOrder(btnIniciarSesionCliente, 0);
        panel.setComponentZOrder(btnIniciarSesionEmpleado, 1);
        panel.setComponentZOrder(btnRegistrarCliente, 2);
        panel.setComponentZOrder(btnSalir, 3);
        panel.setComponentZOrder(backgroundLabel, 4);

        btnIniciarSesionCliente.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Conexion databaseConnector = new Conexion();
                Login_Client iniciar_cliente = new Login_Client(databaseConnector);
                iniciar_cliente.setVisible(true);
                dispose(); // Cierra la ventana actual
            }
        });

        btnIniciarSesionEmpleado.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Login_Employee iniciar_empleado = new Login_Employee();
                iniciar_empleado.setVisible(true);
                dispose(); // Cierra la ventana actual
            }
        });
        btnRegistrarCliente.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                NewClient registrar = new NewClient();
                registrar.setVisible(true);
                dispose(); // Cierra la ventana actual
            }
        });

        btnSalir.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
